# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "metafunction",
    srcs = ["metafunction.cc"],
    copts = [],
    deps = [],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "templateparam",
    srcs = ["templateparam.cc"],
    copts = [],
    deps = [],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "metaobject",
    srcs = ["metaobject.cc"],
    copts = [],
    deps = [],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "metacontrol",
    srcs = ["metacontrol.cc"],
    copts = [],
    deps = [],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "enable_if",
    srcs = ["enable_if.cc"],
    copts = [],
    deps = [],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "compilertimeswitch",
    srcs = ["compilertimeswitch.cc"],
    copts = [],
    deps = [],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "crtp",
    srcs = ["crtp.cc"],
    copts = [],
    deps = [],
)
