# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "metafunction",
    srcs = ["metafunction.cc"],
    copts = [],
    deps = [],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "templateparam",
    srcs = ["templateparam.cc"],
    copts = [],
    deps = [],
)
